name: Build and Test

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.0.x

    - name: Restore dependencies
      run: dotnet restore src/Twikey && dotnet restore src/TwikeyTests

    - name: Build
      run: dotnet build src/Twikey --no-restore && dotnet build src/TwikeyTests --no-restore
 
    - name: Test
      run: dotnet test --no-build --logger "console;verbosity=normal" src/TwikeyTests
      env: 
        TWIKEY_API_KEY: ${{ secrets.TWIKEY_API_KEY }}
        CT: ${{ secrets.CT }}
        mndtNumber: ${{ secrets.mndtNumber }}
