name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/Twikey; dotnet restore src/TwikeyTests
    - name: Build
      run: dotnet build src/Twikey --no-restore; dotnet build src/TwikeyTests --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal src/TwikeyTests
