name: Release to NuGet

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x

    - name: Restore dependencies
      run: dotnet restore src/Twikey && dotnet restore src/TwikeyTests

    - name: Build
      run: dotnet build src/Twikey --no-restore && dotnet build src/TwikeyTests --no-restore

    - name: Publish
      run: (tmpDir=$(mktemp -d) && dotnet pack --no-build src/Twikey --output $tmpDir && dotnet nuget push "$tmpDir/$(ls $tmpDir)" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json); rm -rf $tmpDir
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}